compression-level = 9         # compression level for module zips. between 1 and 9
logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1             # max number of concurrent building jobs
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove its entry
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# extended
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"

[YouTube]       
enabled = true                                            
build-mode = "module"                                                 
excluded-patches = "custom-branding-icon-afn-red custom-branding-icon-afn-blue custom-branding-icon-revancify custom-branding-name"
included-patches = "" 
allow-alpha-version = true                                        
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrvx-magisk"

[Music-arm64]
enabled = true
build-mode = "module"
app-name = "YT-Music"
excluded-patches = "custom-branding-music-afn-red custom-branding-music-afn-blue custom-branding-music-revancify"
included-patches = ""
allow-alpha-version = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-magisk"
arch = "arm64-v8a"

[Music-arm]
enabled = false
build-mode = "module"
app-name = "YT-Music"
excluded-patches = "custom-branding-music-afn-red custom-branding-music-afn-blue custom-branding-music-revancify"
included-patches = ""
allow-alpha-version = true
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrvx-arm-magisk"
arch = "arm-v7a"
